# Generated by Django 4.1.7 on 2023-04-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=100, verbose_name='Last Name')),
                ('username', models.CharField(default='', max_length=100, verbose_name='Username')),
                ('hash', models.CharField(default='', max_length=100)),
                ('salt', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
