# Generated by Django 4.2 on 2023-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MFA', '0003_user_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=100, verbose_name='Password'),
        ),
    ]
